version: '3'

services:
    node:
        container_name: lejeudelavie
        build:
            context: 'docker/node'
        volumes:
            - '.:/app'
        ports:
            - 3003:3003
        env_file:
            - .env
