version: '3'

services:
    node:
        container_name: lejeudelavie_node
        build:
            context: 'docker/node'
        volumes:
            - '.:/app'
        ports:
            - 3000:3000
        env_file:
            - docker/.env
